spring:
  application:
    name: WhiteBox
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      add-mappings: false

server:
  port: 10086